<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//here your code
class Cars{
  
   public $Models;
   public $Year;
   public $color;
   
   function Getowners(){
       $owners=Array("Rami","ahmed","jena");
       return $owners;
       
   }
   
    
    
    
}
